CREATE DATABASE airport;
USE airport;
CREATE TABLE employee_details(employee_name varchar(20), employee_id bigint, phone_no bigint);
ALTER TABLE employee_details ADD COLUMN (address varchar(20),sl_no int,department varchar(10), city_name varchar(15),pincode int);
ALTER TABLE employee_details DROP COLUMN city_name;
ALTER TABLE employee_details DROP COLUMN pincode ;
ALTER TABLE employee_details RENAME COLUMN address TO place;
ALTER TABLE employee_details RENAME COLUMN phone_no TO mobile_no;
ALTER TABLE employee_details RENAME COLUMN employee_name TO worker_name;
ALTER TABLE employee_details RENAME COLUMN department TO sector;
ALTER TABLE employee_details MODIFY COLUMN sl_no bigint;
ALTER TABLE employee_details ADD COLUMN pincode int;
ALTER TABLE employee_details MODIFY COLUMN pincode bigint;
ALTER TABLE employee_details MODIFY COLUMN employee_id int;
ALTER TABLE employee_details MODIFY COLUMN mobile_no int;
ALTER TABLE employee_details MODIFY COLUMN mobile_no bigint;
ALTER TABLE employee_details ADD COLUMN experience int;
ALTER TABLE employee_details MODIFY COLUMN experience bigint;
CREATE TABLE airport_details(airport_name varchar(20),airport_address varchar(20),airport_id bigint);
ALTER TABLE airport_details ADD COLUMN(contact_no bigint,city_name varchar(10), city_pincode int,visa_no int, no_of_passenger int);
ALTER TABLE airport_details DROP COLUMN city_name;
ALTER TABLE airport_details DROP COLUMN airport_name;
ALTER TABLE airport_details RENAME COLUMN airport_id TO airport_no;
ALTER TABLE airport_details RENAME COLUMN airport_address TO airport_place;
ALTER TABLE airport_details RENAME COLUMN city_pincode TO pincode;
ALTER TABLE airport_details RENAME COLUMN visa_no TO visa_id;
ALTER TABLE airport_details RENAME COLUMN no_of_passenger TO passenger_no;
ALTER TABLE airport_details MODIFY COLUMN pincode bigint;
ALTER TABLE airport_details MODIFY COLUMN visa_id bigint;
ALTER TABLE airport_details MODIFY COLUMN contact_no int;
SELECT *FROM employee_details;
INSERT INTO employee_details values('laxmi',1,9844312496,'belagavi',456,'sales',1230,1);
INSERT INTO employee_details values('divya',2,8123791097,'gokak',123,'sales',1230,20);
INSERT INTO employee_details values('bhavya',3,7676663997,'athani',654,'management',0321,30);
INSERT INTO employee_details values('swati',4,9942319810,'terdal',321,'sales',7894,40);
INSERT INTO employee_details values('anu',5,9831249644,'shegunshi',789,'product',4561,50);
INSERT INTO employee_details values('samarth',6,7993666767,'mahalaxmi nagar',987,'sales',3214,60);
INSERT INTO employee_details values('tafseen',7,6667338831,'navanagar',147,'management',6547,70);
INSERT INTO employee_details values('lalita',8,8105627594,'bengaluru',258,'product',6987,80);
INSERT INTO employee_details values('chanagond',9,4957265018,'btm',369,'sales',4568,90);
INSERT INTO employee_details values('rahul',10,9882430400,'rajajinagar',159,'product',4562,100);
SELECT * FROM employee_details where sector='sales';
SELECT * FROM employee_details where employee_id=6;
SELECT * FROM employee_details where place='terdal'; 
